name: Super Cool Workflow
on:
  push:
    branches:
      - 'workflow'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: node
        uses: actions/setup-node@master
        
      - name: build
        run: |
          npm install
          npm run build
          
      - name: list output
        run: ls
        
      - name: deploy to droplet
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with: 
          server: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          ssh_private_key: ${{secrets.KEY}}
          local_path: './*'
          remote_path: '/var/www/html/my_website'
